---

- name: Create Profile Directory
  file:
    path: "{{ oracle_java_profile }}"
    state: directory

- name: Set JAVA_HOME
  template:
    src:  templates/java_home.sh.j2
    dest: "{{ oracle_java_profile }}/java_home.sh"
    mode: 0755
